---

- name: provision battle station
  hosts: "{{ nodes }}"

  vars:

    hostname_format: host

  tasks:

    - name: deploy baseline configuration
      ansible.builtin.include_role:
        name: prov__battle_station
        tasks_from: baseline.yml

    - name: deploy gnome desktop
      ansible.builtin.include_role:
        name: prov__gnome
        tasks_from: base.yml

    - name: deploy gnome tweaks
      ansible.builtin.include_role:
        name: prov__gnome
        tasks_from: tweaks.yml

    - name: enable epel repositories
      ansible.builtin.include_role:
        name: repo__epel

    - name: enable rpm_fusion repositories
      ansible.builtin.include_role:
        name: repo__rpm_fusion

    - name: deploy desktop customizations
      ansible.builtin.include_role:
        name: prov__battle_station
        tasks_from: desktop.yml

    - name: deploy steam
      ansible.builtin.include_role:
        name: prov__steam
        tasks_from: steam.yml

    - name: steam via sudo
      ansible.builtin.include_role:
        name: prov__steam
        tasks_from: sudo.yml

    - name: deploy xone
      ansible.builtin.include_role:
        name: prov__xone

    - name: deploy libvirt
      ansible.builtin.include_role:
        name: prov__kvm
        tasks_from: libvirt.yml

    - name: deploy network bridge
      ansible.builtin.include_role:
        name: prov__kvm
        tasks_from: bridge.yml

...
