---

- name: provision battle station
  hosts: "{{ nodes }}"

  tasks:

    - name: deploy baseline configuration
      include_role:
        name: prov__battle_station
        tasks_from: baseline.yml

    - name: deploy gnome desktop
      include_role:
        name: prov__battle_station
        tasks_from: gnome.yml

    - name: enable epel repositories
      include_role:
        name: repo__epel

    - name: enable rpm_fusion repositories
      include_role:
        name: repo__rpm_fusion

    - name: deploy desktop customizations
      include_role:
        name: prov__battle_station
        tasks_from: desktop.yml

    - name: steam
      include_role:
        name: prov__battle_station
        tasks_from: steam.yml

...
